---
title: "codebook"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Introduction

The `run_analysis.R` script performs the data preparation and then followed by the 5 steps required as described in the course project’s definition.


## Variables

Each row contains, for a given subject and activity, 79 averaged signal measurements.


## Identifiers

-`subject`
    Subject identifier, integer, range from 1 to 30
    
-`activity`
    Activity identifier, string, range in 6 possible values: 
    
	- `WALKING`: subject was walking
	- `WALKING_UPSTAIRS`: subject was walking upstairs
	- `WALKING_DOWNSTAIRS`: subject was walking downstairs
	- `SITTING`: subject was sitting
	- `STANDING`: subject was standing
	- `LAYING`: subject was laying
	
## Final data
- The `tidydata.txt` data file is a text file containing final tidy data. It contains 180 observations and 80 variables.
- The first column is refers to the activity that the subjects were doing, including WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING.
- The second column refers to the id of each subject that did the experiment.

